// ここは自分のSupabase情報に書き換えてください
const SUPABASE_URL = 'https://cxwllytltkaqbjqxrgqa.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4d2xseXRsdGthcWJqcXhyZ3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDg2ODksImV4cCI6MjA2NzYyNDY4OX0.Z68GTGxzokRyarhQz4EfrIqEtr5P5ISNqYWNOXF29x8';

const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
